[project]
name = "flowtograph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "neo4j>=6.1.0",
    "paramiko>=4.0.0",
    "sqlglot>=29.0.1",
]
